services:
  api:
    # path to build context (dockerfile to create dockerimage)
    build: 
      context: ./backend    

    # map port on local machine to port on docker image
    ports:
      - "8000:8000"
    
    # save changes made to the app to your image in real-time. (data will persist the next time the container is run)
    # ./backend is where to save persistent data, /backend is the directory we're grabbing the changes from
    volumes:
      - ./backend:/backend

    # Handles the command used to run the project in the Docker container.  (could we just add this command to this dockerfile ?)
    command: bash -c "python manage.py runserver 0.0.0.0:8000"

  web:
    build: 
      context: ./sprite-animation
    ports:
      - "3000:3000"

    # mount our code in a volume so that we can sync our changes with the container while developing? - look more into this 
    volumes:
      - ./sprite-animation:/frontend
